### ISSUE TITLE
as a suggestion for PVP => PVM

### ISSUE THREAD

**Issue by firelook** [WhiteFang5/VMods#1]
Hello, is it possible to extend your PVP with an other ladder for Player vs Monsters please ?
P.S.
Or Player vs population,.... at the end a statistics of all the kills per population

**Comment by WhiteFang5** [comment]
How do you see this before you?  
Should it also keep track of K/D, or would only Kills be an interesting metric to have?  
Should it have a separate leaderboard for each faction of enemies (bandits, church, creates, etc... ?)

**Comment by firelook** [comment]
As much as detailed as possible.
Later I suspect he should be fun to have a web page to show statistics per people ;)

**Comment by WhiteFang5** [comment]
After some tinkering, I came up with a first version that support a slew of leaderboards for each faction, blood type and an overall leaderboard for pve.

https://github.com/WhiteFang5/VMods/releases/tag/PvELeaderboard-v1.0.0
