### ISSUE TITLE
Blood Refill Log Laggy

### ISSUE THREAD

**Issue by Airyn-Akyn** [WhiteFang5/VMods#3]
I got a small freeze everytime i feed. with other mods it come from the log line in the chat. Should had an way to disable it.

**Comment by WhiteFang5** [comment]
Hi, thank you for reporting this. I've been considering adding an option to opt-in to the chat messages (with the default being off). So I'll be looking into adding that feature soon™

**Comment by WhiteFang5** [comment]
Both a config option and chat command to toggle the chat messages on/off has been added to the Blood Refill mod in v1.0.1
(https://github.com/WhiteFang5/VMods/releases/tag/BloodRefill-v1.0.1)
